// <auto-generated />
namespace Tax_Return_BD_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191140113_intial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
